// Code generated by mockery v1.0.0
package automock

import mock "github.com/stretchr/testify/mock"
import printer "github.com/pkosiec/terminer/internal/printer"
import recipe "github.com/pkosiec/terminer/pkg/recipe"

// Printer is an autogenerated mock type for the Printer type
type Printer struct {
	mock.Mock
}

// Command provides a mock function with given fields: cmd
func (_m *Printer) Command(cmd string) {
	_m.Called(cmd)
}

// ExecError provides a mock function with given fields: output
func (_m *Printer) ExecError(output string) {
	_m.Called(output)
}

// ExecOutput provides a mock function with given fields: output
func (_m *Printer) ExecOutput(output string) {
	_m.Called(output)
}

// Recipe provides a mock function with given fields: r
func (_m *Printer) Recipe(r recipe.UnitMetadata) {
	_m.Called(r)
}

// SetContext provides a mock function with given fields: operation, stagesCount
func (_m *Printer) SetContext(operation printer.Operation, stagesCount int) {
	_m.Called(operation, stagesCount)
}

// Stage provides a mock function with given fields: stageIndex, s
func (_m *Printer) Stage(stageIndex int, s recipe.Stage) {
	_m.Called(stageIndex, s)
}

// Step provides a mock function with given fields: stepIndex, steps, s
func (_m *Printer) Step(stepIndex int, steps int, s recipe.UnitMetadata) {
	_m.Called(stepIndex, steps, s)
}
