os: darwin
metadata:
  name: Fish Starter
  description: Set up Fish shell with useful plugins

stages:
  - metadata:
      name: Fish Shell
      url: https://fishshell.com/
    steps:
      - metadata:
          name: Download
        execute:
          run:
            - curl https://github.com/fish-shell/fish-shell/releases/download/3.0.2/fish-3.0.2.pkg --create-dirs -sLo ~/.temp/fish-installer.pkg
        rollback:
          run:
            - rm -rf ~/.temp
      - metadata:
          name: Install
        execute:
          run:
            - installer -pkg ~/.temp/fish-installer.pkg -target /
          root: true
        rollback:
          run:
            - rm -Rf /usr/local/etc/fish /usr/local/share/fish ~/.config/fish
            - cd /usr/local/bin
            - rm -f fish mimedb fish_pager fishd fish_indent
            - yes | rm /usr/local/share/man/man1/fish*.1
          root: true
      - metadata:
          name: Cleanup
        execute:
          run:
            - rm -rf ~/.temp

  - metadata:
      name: Fisher Package manager
      url: https://github.com/jorgebucaran/fisher
    steps:
      - execute:
          run:
            - curl https://git.io/fisher --create-dirs -sLo ~/.config/fish/functions/fisher.fish
          shell: fish
        rollback:
          run:
            - fisher self-uninstall
          shell: fish

  - metadata:
      name: Useful Fish packages
    steps:
      - metadata:
          name: franciscolourenco/done
          url: https://github.com/franciscolourenco/done
        execute:
          run:
            - fisher add franciscolourenco/done
          shell: fish
        rollback:
          run:
            - fisher rm franciscolourenco/done
          shell: fish
      - metadata:
          name: jethrokuan/z
          url: https://github.com/jethrokuan/z
        execute:
          run:
            - fisher add jethrokuan/z
          shell: fish
        rollback:
          run:
            - fisher rm jethrokuan/z
          shell: fish

  - metadata:
      name: Pure Prompt
      url: https://github.com/rafaelrinaldi/pure
    steps:
      - metadata:
          name: Download & Install
        execute:
          run:
            - fisher add rafaelrinaldi/pure
          shell: fish
        rollback:
          run:
            - fisher rm rafaelrinaldi/pure
          shell: fish

  - metadata:
      name: Powerline fonts
      url: https://github.com/powerline/fonts
    steps:
      - metadata:
          name: Download
        execute:
          run: 
            - git clone https://github.com/powerline/fonts ~/.terminer/powerline-fonts
      - metadata:
          name: Install
        execute:
          run:
            - ~/.terminer/powerline-fonts/install.sh
            - rm -rf ~/.terminer/powerline-fonts
            - echo "**NOTE:** Fonts installed successfully. After recipe installation, set the 'Meslo' font in your terminal emulator."
        rollback:
          run:
            - git clone https://github.com/powerline/fonts ~/.terminer/powerline-fonts
            - ~/.terminer/powerline-fonts/uninstall.sh
            - rm -rf ~/.terminer/powerline-fonts
          root: true

  - metadata:
      name: Set as default shell
    steps:
      - execute:
          run:
            - chsh -s $(which fish)
          root: true
        rollback:
          run:
            - chsh -s $(which bash)
          root: true