os: linux
metadata:
  name: Fish Starter
  description: Set up Fish shell with useful plugins

stages:
  - metadata:
      name: Fish Shell
      url: https://fishshell.com/
    steps:
      - metadata:
          name: Download & Install
          url: https://fishshell.com/
        execute:
          run:
            - sudo apt-get update
            - sudo apt-get install -y git curl
            - sudo apt-get -y install fish
        rollback:
          run:
            - sudo apt-get -y remove fish

  - metadata:
      name: Fisher - Package manager
      url: https://github.com/jorgebucaran/fisher
    steps:
      - execute:
          run:
            - curl https://git.io/fisher --create-dirs -sLo ~/.config/fish/functions/fisher.fish
          shell: fish
        rollback:
          run:
            - fisher self-uninstall
          shell: fish

  - metadata:
      name: Useful Fish packages
    steps:
      - metadata:
          name: franciscolourenco/done
          url: https://github.com/franciscolourenco/done
        execute:
          run:
            - fisher install franciscolourenco/done
          shell: fish
        rollback:
          run:
            - fisher remove franciscolourenco/done
          shell: fish
      - metadata:
          name: jethrokuan/z
          url: https://github.com/jethrokuan/z
        execute:
          run:
            - fisher install jethrokuan/z
          shell: fish
        rollback:
          run:
            - fisher remove jethrokuan/z
          shell: fish

  - metadata:
      name: Pure Prompt
      url: https://github.com/rafaelrinaldi/pure
    steps:
      - metadata:
          name: Download & Install
        execute:
          run:
            - fisher install rafaelrinaldi/pure
          shell: fish
        rollback:
          run:
            - fisher remove rafaelrinaldi/pure
          shell: fish

  - metadata:
      name: Powerline fonts
      url: https://github.com/powerline/fonts
    steps:
      - metadata:
          name: Download
        execute:
          run: 
            - git clone https://github.com/powerline/fonts ~/.terminer/powerline-fonts
      - metadata:
          name: Install
        execute:
          run:
            - ~/.terminer/powerline-fonts/install.sh
            - rm -rf ~/.terminer/powerline-fonts
            - echo "**NOTE:** Fonts installed successfully. After recipe installation, set the 'Meslo' font in your terminal emulator."
        rollback:
          run:
            - git clone https://github.com/powerline/fonts ~/.terminer/powerline-fonts
            - ~/.terminer/powerline-fonts/uninstall.sh
            - rm -rf ~/.terminer/powerline-fonts
          root: true

  - metadata:
      name: Set as default shell
    steps:
      - execute:
          run:
            - chsh -s $(which fish)
          root: true
        rollback:
          run:
            - chsh -s $(which bash)
          root: true
