builds:
- env:
  - CGO_ENABLED=0
  goos:
    - freebsd
    - darwin
    - linux
  ldflags:
    - -s -w -X "github.com/pkosiec/terminer/internal/metadata.Version={{.Version}}"
archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc

