builds:
- env:
  - CGO_ENABLED=0
  goos:
    - freebsd
    - darwin
    - linux
  goarch:
    - 386
    - amd64
    - arm
    - arm64
  ldflags:
    - -s -w -X "github.com/pkosiec/terminer/internal/metadata.Version={{.Version}}"
archives:
  - id: default
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"

