language: go

services:
  - docker

branches:
  only:
    - master
    - /^v?(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*)?(\+[0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*)?$/

go:
  - 1.15.x

install:
  - go mod download

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./...
  - go build main.go && rm main

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  - provider: script
    skip_cleanup: true
    script: bash ./ci/deploy.sh
    on:
      tags: true