language: go

branches:
  only:
    - master
    - /^v?(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*)?(\+[0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*)?$/

go:
  - 1.11.x

before_install:
  - DEP_RELEASE_TAG='v0.4.1' curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

install:
  - dep ensure -v -vendor-only

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./...
  - go build main.go && rm main

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true