// Code generated by mockery v1.0.0
package automock

import mock "github.com/stretchr/testify/mock"
import shell "github.com/pkosiec/terminer/pkg/shell"

// Shell is an autogenerated mock type for the Shell type
type Shell struct {
	mock.Mock
}

// Exec provides a mock function with given fields: command
func (_m *Shell) Exec(command shell.Command) (string, error) {
	ret := _m.Called(command)

	var r0 string
	if rf, ok := ret.Get(0).(func(shell.Command) string); ok {
		r0 = rf(command)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(shell.Command) error); ok {
		r1 = rf(command)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
