// Code generated by mockery v1.0.0
package automock

import mock "github.com/stretchr/testify/mock"
import shell "github.com/pkosiec/terminer/pkg/shell"

// Shell is an autogenerated mock type for the Shell type
type Shell struct {
	mock.Mock
}

// Exec provides a mock function with given fields: command, outputPrinter, errPrinter
func (_m *Shell) Exec(command shell.Command, outputPrinter shell.PrintFn, errPrinter shell.PrintFn) error {
	ret := _m.Called(command, outputPrinter, errPrinter)

	var r0 error
	if rf, ok := ret.Get(0).(func(shell.Command, shell.PrintFn, shell.PrintFn) error); ok {
		r0 = rf(command, outputPrinter, errPrinter)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
