// Code generated by mockery v1.0.0
package automock

import mock "github.com/stretchr/testify/mock"

// Shell is an autogenerated mock type for the Shell type
type Shell struct {
	mock.Mock
}

// Exec provides a mock function with given fields: _a0, command
func (_m *Shell) Exec(_a0 string, command string) (string, error) {
	ret := _m.Called(_a0, command)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(_a0, command)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(_a0, command)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
