// Code generated by mockery v1.0.0
package automock

import mock "github.com/stretchr/testify/mock"

// Sh is an autogenerated mock type for the Sh type
type Sh struct {
	mock.Mock
}

// Exec provides a mock function with given fields: command
func (_m *Sh) Exec(command string) (string, error) {
	ret := _m.Called(command)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(command)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(command)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExecInDir provides a mock function with given fields: command, dir
func (_m *Sh) ExecInDir(command string, dir string) (string, error) {
	ret := _m.Called(command, dir)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(command, dir)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(command, dir)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
